#!/bin/bash 
# Jan Kwinta
#
# 16.10.2025
#
# Problem SHELL02
# Program 1
set -e

# sprawdzenie opcji -q
while getopts "q" flag; do
    case ${flag} in
        q) echo "Unsupported option: -q"
        exit 1
        ;;
    esac
done

# wypisanie obecnych flag opcji
while getopts "abcde" flag; do
    case ${flag} in
        a) echo "-a present"
        ;;
        b) echo "-b present"
        ;;
        c) echo "-c present"
        ;;
        d) echo "-d present"
        ;;
        e) echo "-e present"
        ;;
        q) echo "Unsupported option: -q"
        ;;
    esac
done

# wypisanie argumentow
argNum=$#
optNum=$OPTIND
if (( argNum > 0 )) ; then
    echo "Arguments are:"
    for i in $(seq $optNum $argNum) ; do
        ind=$((i - optNum + 1))
        echo "\$${ind} = ${!i}"
    done
fi