#!/bin/bash 
# Jan Kwinta
#
# 16.10.2025
#
# Problem SHELL02
# Program 1
set -e

options=()
for i in {1..26}; do 
    options+=(0); 
done

# sprawdzenie obecnych flag opcji
# i zaznaczenie tego w tablicy
while getopts "qabcdefghijklmnoprstuvwxyz" flag; do
    if [[ $flag == "q" ]]; then
        options[0]=1
    else
        index=$(( $(printf "%d" "'$flag") - 96 ))
        options[$index]=1
    fi
done

# wypisanie argumentow
argNum=$#
optNum=$OPTIND
if (( argNum > 0 )) ; then
    echo "Arguments are:"
    for i in $(seq $optNum $argNum) ; do
        ind=$((i - optNum + 1))
        echo "\$${ind} = ${!i}"
    done
fi