#!/bin/bash 
# Jan Kwinta
#
# 17.10.2025
#
# Problem SHELL02
# Program 2
set -e

# parsowanie argumentow getopt
SHORT_OPTS=":i:o:qabcdefghijklmnoprstuvwxyz"
LONG_OPTS="help"

PARSED=$(getopt --options="$SHORT_OPTS" --longoptions="$LONG_OPTS" --name "$0" -- "$@") || {
    echo "-i -o options require a filename"
    exit 3
}
eval set -- "$PARSED"

options=($(printf '0 %.0s' {1..26}))
inputFile=""
outputFile=""
qPresent=0

# sprawdzenie obecnych flag opcji
# i zaznaczenie tego w tablicy
while true ; do
    case "$1" in
        --help)
            echo "help"
            exit 1
            ;;
        -q)
            qPresent=1
            shift
            ;;
        -i)            
            options[$(( $(printf "%d" "'i") - 97 ))]=1
            inputFile="$2"
            shift 2
            ;;
        -o)
            options[$(( $(printf "%d" "'o") - 97 ))]=1
            outputFile="$2"
            shift 2
            ;;
        -[a-hj-np-z])
            flag="${1:1}"
            options[$(( $(printf "%d" "'$flag") - 97 ))]=1
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "Internal error: $1"
            exit 99
            ;;
  esac
done

# wypisanie dla opcji q
if [[ $qPresent == 1 ]] ; then
    echo "Unsupported option: -q"
    exit 2
fi

# jako nazwa pliku zostala wczytana flaga
if [[ $inputFile == -* || $outputFile == -* ]] ; then
    echo "-i -o options require a filename"
    exit 3
fi

# wypisanie obecnych opcji
# a dla -i oraz -o wypisanie nazw plikow
for ((i = 0; i < 26; i++)); do
    letter=$(printf "\\$(printf '%03o' $((97 + i)))")

    if [[  ${options[i]} == 1  ]] ; then
        if [[ $letter == "i" ]] ; then
            echo "-i present and set to \"$inputFile\""
        elif [[ $letter == "o" ]] ; then
            echo "-o present and set to \"$outputFile\""
        else
            echo "-$letter present"
        fi
    fi
done

# wypisanie argumentow
if [[  $# > 0  ]] ; then
    echo "Arguments are:"
    ind=1
    for arg in "$@"; do
        echo "\$${ind}=$arg"
        ((ind++))
    done
fi