#!/bin/bash 
# Jan Kwinta
#
# 17.10.2025
#
# Problem SHELL02
# Program 2
set -e

## parsowanie linii argumentow
OPTS=$(getopt -o ioqabcdefghijklmnoprstuvwxyz --long help -n 'arg2' -- "$@")

if [ $? -ne 0 ]; then
  echo "Failed to parse options" >&2
  exit 1
fi

eval set -- "$OPTS"


options=($(printf '0 %.0s' {1..26}))

# sprawdzenie obecnych flag opcji
# i zaznaczenie tego w tablicy
while true; do
    case "$1" in
        --help)
            echo "help"
            exit 2
            ;;
        -q)
            # jesli jest -q zakonczenie programu
            echo "Unsupported option: -q"
            exit 3
            ;;
        -i)
            # jesli jest opcja -i zapamietujemy nazwe pliku
            options[$(( $(printf "%d" "'${1:1}") - 97 ))]=1
            inputFile="$2"
            shift 2
            ;;
        -o)
            # jesli jest opcja -o zapamietujemy nazwe pliku
            options[$(( $(printf "%d" "'${1:1}") - 97 ))]=1
            outputFile="$2"
            shift 2
            ;;
        *)
            options[$(( $(printf "%d" "'${1:1}") - 97 ))]=1
            ;;
  esac
done

# jako nazwa pliku zostala wczytana flaga
if [[ $inputFile == -* || $outputFile == -* ]] ; then
    echo "-i -o options require a filename"
    exit 1
fi

# wypisanie obecnych opcji
# a dla -i oraz -o wypisanie nazw plikow
for ((i = 0; i < 26; i++)); do
    letter=$(printf "\\$(printf '%03o' $((97 + i)))")

    if (( ${options[i]} == 1 )) ; then
        if [[ $letter == "i" ]] ; then
            echo "-i present and set to \"$inputFile\""
        elif [[ $letter == "o" ]] ; then
            echo "-o present and set to \"$outputFile\""
        else
            echo "-$letter present"
        fi
    fi
done

# wypisanie argumentow
# argNum=$#
# optNum=$OPTIND
# if (( $((argNum - optNum + 1)) > 0 )) ; then
#     echo "Arguments are:"
#     for i in $(seq $optNum $argNum) ; do
#         ind=$((i - optNum + 1))
#         echo "\$${ind}=${!i}"
#     done
# fi